# Generated by Django 5.2.8 on 2026-02-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahal_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bg_color', models.CharField(blank=True, max_length=100, null=True)),
                ('font_color', models.CharField(blank=True, max_length=100, null=True)),
                ('font_size', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='logo/')),
                ('logo_radius', models.IntegerField(default=40)),
            ],
        ),
    ]
