# Generated by Django 5.2.8 on 2026-02-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahalApp', '0002_homeslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
